const contactConstants = {
    GETALL_REQUEST: 'CONTACTS_GETALL_REQUEST',
    GETALL_SUCCESS: 'CONTACTS_GETALL_SUCCESS',
    GETALL_FAILURE: 'CONTACTS_GETALL_FAILURE',

    GET_REQUEST: 'CONTACT_GET_REQUEST',
    GET_SUCCESS: 'CONTACT_GET_SUCCESS',
    GET_FAILURE: 'CONTACT_GET_FAILURE',

    UPDATE_REQUEST: 'CONTACT_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'CONTACT_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'CONTACT_UPDATE_FAILURE',

    NEW_REQUEST: 'CONTACT_NEW_REQUEST',
    NEW_SUCCESS: 'CONTACT_NEW_SUCCESS',
    NEW_FAILURE: 'CONTACT_NEW_FAILURE',

    CREATE_REQUEST: 'CONTACT_CREATE_REQUEST',
    CREATE_SUCCESS: 'CONTACT_CREATE_SUCCESS',
    CREATE_FAILURE: 'CONTACT_CREATE_FAILURE',

    DELETE_REQUEST: 'CONTACTS_DELETE_REQUEST',
    DELETE_SUCCESS: 'CONTACTS_DELETE_SUCCESS',
    DELETE_FAILURE: 'CONTACTS_DELETE_FAILURE'
};

export default contactConstants;