export const mesaConstants = {
    GETALL_REQUEST: 'MESAS_GETALL_REQUEST',
    GETALL_SUCCESS: 'MESAS_GETALL_SUCCESS',
    GETALL_FAILURE: 'MESAS_GETALL_FAILURE',

    GET_REQUEST: 'MESAS_GET_REQUEST',
    GET_SUCCESS: 'MESAS_GET_SUCCESS',
    GET_FAILURE: 'MESAS_GET_FAILURE',

    DELETE_REQUEST: 'MESAS_DELETE_REQUEST',
    DELETE_SUCCESS: 'MESAS_DELETE_SUCCESS',
    DELETE_FAILURE: 'MESAS_DELETE_FAILURE'
};
