export const pedidoConstants = {
    GETALL_REQUEST: 'PEDIDOS_GETALL_REQUEST',
    GETALL_SUCCESS: 'PEDIDOS_GETALL_SUCCESS',
    GETALL_FAILURE: 'PEDIDOS_GETALL_FAILURE',

    GET_REQUEST: 'PEDIDOS_GET_REQUEST',
    GET_SUCCESS: 'PEDIDOS_GET_SUCCESS',
    GET_FAILURE: 'PEDIDOS_GET_FAILURE',

    GETBYMESA_REQUEST: 'PEDIDOSBYMESA_GET_REQUEST',
    GETBYMESA_SUCCESS: 'PEDIDOSBYMESA_GET_SUCCESS',
    GETBYMESA_FAILURE: 'PEDIDOSBYMESA_GET_FAILURE',


    DELETE_REQUEST: 'PEDIDOS_DELETE_REQUEST',
    DELETE_SUCCESS: 'PEDIDOS_DELETE_SUCCESS',
    DELETE_FAILURE: 'PEDIDOS_DELETE_FAILURE'
};
